spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://localhost:3306/insurai_db?createDatabaseIfNotExist=true
    username: root
    password: test123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: c29tZVN1cGVyU2VjcmV0S2V5VGhhdElzTG9uZ0Vub3VnaEZvckhTMjU2QWxnb3JpdGht
  expiration-ms: 86400000

razorpay:
  key-id: rzp_test_TW6VxZoZ26UhvN
  key-secret: oeJc74k9SFwqwdmzAzEIuxjW